package com.rmf.rdvp.audit;

public enum AuditAction {
    AUTH_LOGIN,
    AUTHENTICATION_FAILED,
    AUTH_PASSWORD_VERIFY,
    AUTHORIZATION_DENIED,
    OFFLINE_SYNC,
    DEVICE_VERIFICATION,
    DEVICE_CHANGE_REQUEST,
    DEVICE_CHANGE_REVIEW,
    FAULT_REPORT,
    REPAIR_TASK_ACCEPT,
    REPAIR_REPORT,
    REINSPECTION_RECORD
}
