ALTER TABLE IF EXISTS archive_devices RENAME CONSTRAINT devices_pkey TO pk_archive_devices;
ALTER TABLE IF EXISTS archive_devices RENAME CONSTRAINT devices_device_code_key TO uq_archive_devices_device_code;

ALTER TABLE IF EXISTS archive_device_qr_codes RENAME CONSTRAINT device_qrcodes_pkey TO pk_archive_device_qr_codes;
ALTER TABLE IF EXISTS archive_device_qr_codes RENAME CONSTRAINT device_qrcodes_nonce_key TO uq_archive_device_qr_codes_nonce;
ALTER TABLE IF EXISTS archive_device_qr_codes RENAME CONSTRAINT device_qrcodes_device_id_fkey TO fk_archive_device_qr_codes_device;

ALTER TABLE IF EXISTS operations_device_verification_reports RENAME CONSTRAINT device_verification_records_pkey TO pk_operations_device_verification_reports;
ALTER TABLE IF EXISTS operations_device_verification_reports RENAME CONSTRAINT device_verification_records_device_id_fkey TO fk_operations_device_verification_reports_device;

ALTER TABLE IF EXISTS operations_fault_reports RENAME CONSTRAINT fault_reports_pkey TO pk_operations_fault_reports;
ALTER TABLE IF EXISTS operations_fault_reports RENAME CONSTRAINT fault_reports_fault_report_no_key TO uq_operations_fault_reports_fault_report_no;
ALTER TABLE IF EXISTS operations_fault_reports RENAME CONSTRAINT fault_reports_device_id_fkey TO fk_operations_fault_reports_device;

ALTER TABLE IF EXISTS operations_repair_tasks RENAME CONSTRAINT repair_tasks_pkey TO pk_operations_repair_tasks;
ALTER TABLE IF EXISTS operations_repair_tasks RENAME CONSTRAINT repair_tasks_repair_task_no_key TO uq_operations_repair_tasks_repair_task_no;
ALTER TABLE IF EXISTS operations_repair_tasks RENAME CONSTRAINT repair_tasks_fault_report_id_fkey TO fk_operations_repair_tasks_fault_report;

ALTER TABLE IF EXISTS operations_repair_reports RENAME CONSTRAINT repair_reports_pkey TO pk_operations_repair_reports;
ALTER TABLE IF EXISTS operations_repair_reports RENAME CONSTRAINT repair_reports_repair_report_no_key TO uq_operations_repair_reports_repair_report_no;
ALTER TABLE IF EXISTS operations_repair_reports RENAME CONSTRAINT repair_reports_repair_task_id_key TO uq_operations_repair_reports_repair_task;
ALTER TABLE IF EXISTS operations_repair_reports RENAME CONSTRAINT repair_reports_repair_task_id_fkey TO fk_operations_repair_reports_repair_task;
ALTER TABLE IF EXISTS operations_repair_reports RENAME CONSTRAINT repair_reports_fault_report_id_fkey TO fk_operations_repair_reports_fault_report;

ALTER TABLE IF EXISTS operations_reinspection_reports RENAME CONSTRAINT reinspection_records_pkey TO pk_operations_reinspection_reports;
ALTER TABLE IF EXISTS operations_reinspection_reports RENAME CONSTRAINT reinspection_records_reinspection_record_no_key TO uq_operations_reinspection_reports_reinspection_report_no;
ALTER TABLE IF EXISTS operations_reinspection_reports RENAME CONSTRAINT reinspection_records_fault_report_id_fkey TO fk_operations_reinspection_reports_fault_report;
ALTER TABLE IF EXISTS operations_reinspection_reports RENAME CONSTRAINT reinspection_records_repair_report_id_fkey TO fk_operations_reinspection_reports_repair_report;

ALTER TABLE IF EXISTS review_archive_requests RENAME CONSTRAINT device_archive_requests_pkey TO pk_review_archive_requests;
ALTER TABLE IF EXISTS review_archive_requests RENAME CONSTRAINT device_archive_requests_device_id_fkey TO fk_review_archive_requests_device;

ALTER TABLE IF EXISTS review_operations_requests RENAME CONSTRAINT operations_review_requests_pkey TO pk_review_operations_requests;
ALTER TABLE IF EXISTS review_operations_requests RENAME CONSTRAINT operations_review_requests_fault_report_id_fkey TO fk_review_operations_requests_fault_report;
ALTER TABLE IF EXISTS review_operations_requests RENAME CONSTRAINT operations_review_requests_device_id_fkey TO fk_review_operations_requests_device;

ALTER TABLE IF EXISTS log_entries RENAME CONSTRAINT audit_logs_pkey TO pk_log_entries;

ALTER TABLE IF EXISTS user_accounts RENAME CONSTRAINT users_pkey TO pk_user_accounts;
ALTER TABLE IF EXISTS user_accounts RENAME CONSTRAINT users_username_key TO uq_user_accounts_username;

ALTER TABLE IF EXISTS user_account_roles RENAME CONSTRAINT user_roles_pkey TO pk_user_account_roles;
ALTER TABLE IF EXISTS user_account_roles RENAME CONSTRAINT user_roles_user_id_fkey TO fk_user_account_roles_user_account;

ALTER TABLE IF EXISTS user_account_permissions RENAME CONSTRAINT user_permissions_pkey TO pk_user_account_permissions;
ALTER TABLE IF EXISTS user_account_permissions RENAME CONSTRAINT user_permissions_user_id_fkey TO fk_user_account_permissions_user_account;

ALTER TABLE IF EXISTS user_token_sessions RENAME CONSTRAINT token_sessions_pkey TO pk_user_token_sessions;
ALTER TABLE IF EXISTS user_token_sessions RENAME CONSTRAINT token_sessions_token_hash_key TO uq_user_token_sessions_token_hash;
ALTER TABLE IF EXISTS user_token_sessions RENAME CONSTRAINT token_sessions_user_id_fkey TO fk_user_token_sessions_user_account;

ALTER TABLE IF EXISTS user_password_verification_attempts RENAME CONSTRAINT password_verification_attempts_pkey TO pk_user_password_verification_attempts;
ALTER TABLE IF EXISTS user_password_verification_attempts RENAME CONSTRAINT password_verification_attempts_user_id_fkey TO fk_user_password_verification_attempts_user_account;
ALTER TABLE IF EXISTS user_password_verification_attempts RENAME CONSTRAINT password_verification_attempts_failed_count_check TO ck_user_password_verification_attempts_failed_count_nonnegative;

ALTER TABLE IF EXISTS user_login_attempts RENAME CONSTRAINT login_attempts_pkey TO pk_user_login_attempts;
ALTER TABLE IF EXISTS user_login_attempts RENAME CONSTRAINT login_attempts_failed_count_check TO ck_user_login_attempts_failed_count_nonnegative;

ALTER INDEX IF EXISTS idx_devices_location_geography RENAME TO idx_archive_devices_location_geography;
ALTER INDEX IF EXISTS idx_fault_reports_status_updated RENAME TO idx_operations_fault_reports_status_updated;
ALTER INDEX IF EXISTS ux_fault_reports_active_device RENAME TO ux_operations_fault_reports_active_device;
ALTER INDEX IF EXISTS idx_repair_tasks_maintainer_status_type RENAME TO idx_operations_repair_tasks_maintainer_status_type;
ALTER INDEX IF EXISTS idx_repair_reports_fault_created RENAME TO idx_operations_repair_reports_fault_created;
ALTER INDEX IF EXISTS idx_device_archive_requests_initiated_at RENAME TO idx_review_archive_requests_initiated_at;
ALTER INDEX IF EXISTS ux_device_archive_requests_pending_target_code RENAME TO ux_review_archive_requests_pending_target_code;
