UPDATE user_account_permissions
SET permission_code = CASE permission_code
    WHEN 'ARCHIVE_CENTER_DEVICE_ARCHIVE_QUERY' THEN 'ARCHIVE_CENTER_ARCHIVE_QUERY'
    WHEN 'ARCHIVE_CENTER_DEVICE_ARCHIVE_CREATE_REQUEST_SUBMIT' THEN 'ARCHIVE_CENTER_ARCHIVE_CREATE_REQUEST_SUBMIT'
    WHEN 'ARCHIVE_CENTER_DEVICE_ARCHIVE_UPDATE_REQUEST_SUBMIT' THEN 'ARCHIVE_CENTER_ARCHIVE_UPDATE_REQUEST_SUBMIT'
    WHEN 'ARCHIVE_CENTER_DEVICE_ARCHIVE_DELETE_REQUEST_SUBMIT' THEN 'ARCHIVE_CENTER_ARCHIVE_DELETE_REQUEST_SUBMIT'
    WHEN 'ARCHIVE_CENTER_DEVICE_ARCHIVE_EXPORT' THEN 'ARCHIVE_CENTER_ARCHIVE_EXPORT'
    WHEN 'MANAGEMENT_CENTER_DEVICE_ARCHIVE_REQUEST_REVIEW' THEN 'REVIEW_CENTER_ARCHIVE_REQUEST_REVIEW'
    WHEN 'REVIEW_CENTER_DEVICE_ARCHIVE_REQUEST_REVIEW' THEN 'REVIEW_CENTER_ARCHIVE_REQUEST_REVIEW'
    ELSE permission_code
END
WHERE permission_code IN (
    'ARCHIVE_CENTER_DEVICE_ARCHIVE_QUERY',
    'ARCHIVE_CENTER_DEVICE_ARCHIVE_CREATE_REQUEST_SUBMIT',
    'ARCHIVE_CENTER_DEVICE_ARCHIVE_UPDATE_REQUEST_SUBMIT',
    'ARCHIVE_CENTER_DEVICE_ARCHIVE_DELETE_REQUEST_SUBMIT',
    'ARCHIVE_CENTER_DEVICE_ARCHIVE_EXPORT',
    'MANAGEMENT_CENTER_DEVICE_ARCHIVE_REQUEST_REVIEW',
    'REVIEW_CENTER_DEVICE_ARCHIVE_REQUEST_REVIEW'
);

DELETE FROM user_account_permissions stale
USING user_account_permissions kept
WHERE stale.ctid < kept.ctid
  AND stale.user_id = kept.user_id
  AND stale.permission_code = kept.permission_code;

UPDATE log_entries
SET action = CASE action
    WHEN 'DEVICE_ARCHIVE_QUERY' THEN 'ARCHIVE_QUERY'
    WHEN 'DEVICE_ARCHIVE_EXPORT' THEN 'ARCHIVE_EXPORT'
    WHEN 'DEVICE_ARCHIVE_REQUEST' THEN 'ARCHIVE_REQUEST'
    WHEN 'DEVICE_ARCHIVE_REVIEW' THEN 'ARCHIVE_REVIEW'
    ELSE action
END
WHERE action IN (
    'DEVICE_ARCHIVE_QUERY',
    'DEVICE_ARCHIVE_EXPORT',
    'DEVICE_ARCHIVE_REQUEST',
    'DEVICE_ARCHIVE_REVIEW'
);

UPDATE log_entries
SET description = CASE description
    WHEN '查询设备档案。' THEN '查询档案。'
    WHEN '导出设备档案。' THEN '导出档案。'
    ELSE description
END
WHERE description IN (
    '查询设备档案。',
    '导出设备档案。'
);

UPDATE review_archive_requests
SET reason = CASE reason
    WHEN '新增设备档案。' THEN '新增档案。'
    ELSE reason
END
WHERE reason IN (
    '新增设备档案。'
);
