export class AppRoutes {
  static readonly LoginPage: string = 'user/pages/LoginPage';
  static readonly HomePage: string = 'home/pages/HomePage';
  static readonly UserCenterPage: string = 'user/pages/UserCenterPage';
  static readonly UserSettingsPage: string = 'user/pages/UserSettingsPage';
  static readonly ArchiveCenterPage: string = 'archive/pages/ArchiveCenterPage';
  static readonly DeviceArchiveQueryPage: string = 'archive/pages/DeviceArchiveQueryPage';
  static readonly DeviceArchiveCreatePage: string = 'archive/pages/DeviceArchiveCreatePage';
  static readonly DeviceArchiveDetailPage: string = 'archive/pages/DeviceArchiveDetailPage';
  static readonly DeviceArchiveExportPage: string = 'archive/pages/DeviceArchiveExportPage';
  static readonly DeviceArchiveUpdatePage: string = 'archive/pages/DeviceArchiveUpdatePage';
  static readonly DeviceArchiveDeletePage: string = 'archive/pages/DeviceArchiveDeletePage';
  static readonly OperationsCenterPage: string = 'operations/pages/OperationsCenterPage';
  static readonly DeviceVerificationAndFaultReportPage: string =
    'operations/pages/DeviceVerificationAndFaultReportPage';
  static readonly TaskAcceptancePage: string = 'operations/pages/TaskAcceptancePage';
  static readonly RepairAndReinspectionPage: string = 'operations/pages/RepairAndReinspectionPage';
  static readonly ReviewCenterPage: string = 'review/pages/ReviewCenterPage';
  static readonly ArchiveReviewPage: string = 'review/pages/ArchiveReviewPage';
  static readonly OperationsReviewPage: string = 'review/pages/OperationsReviewPage';
  static readonly LogCenterPage: string = 'log/pages/LogCenterPage';
  static readonly ArchiveLogQueryPage: string = 'log/pages/ArchiveLogQueryPage';
  static readonly OperationsLogQueryPage: string = 'log/pages/OperationsLogQueryPage';
}
