export class AppRoutes {
  static readonly LoginPage: string = 'user/pages/LoginPage';
  static readonly HomePage: string = 'home/pages/HomePage';
  static readonly UserCenterPage: string = 'user/pages/UserCenterPage';
  static readonly UserSettingsPage: string = 'user/pages/UserSettingsPage';
  static readonly ArchiveCenterPage: string = 'archive/pages/ArchiveCenterPage';
  static readonly ArchiveQueryPage: string = 'archive/pages/ArchiveQueryPage';
  static readonly ArchiveCreatePage: string = 'archive/pages/ArchiveCreatePage';
  static readonly ArchiveDetailPage: string = 'archive/pages/ArchiveDetailPage';
  static readonly ArchiveExportPage: string = 'archive/pages/ArchiveExportPage';
  static readonly ArchiveUpdatePage: string = 'archive/pages/ArchiveUpdatePage';
  static readonly ArchiveDeletePage: string = 'archive/pages/ArchiveDeletePage';
  static readonly OperationsCenterPage: string = 'operations/pages/OperationsCenterPage';
  static readonly VerificationAndFaultReportPage: string =
    'operations/pages/VerificationAndFaultReportPage';
  static readonly TaskAcceptancePage: string = 'operations/pages/TaskAcceptancePage';
  static readonly RepairAndReinspectionPage: string = 'operations/pages/RepairAndReinspectionPage';
  static readonly ReviewCenterPage: string = 'review/pages/ReviewCenterPage';
  static readonly ArchiveReviewPage: string = 'review/pages/ArchiveReviewPage';
  static readonly OperationsReviewPage: string = 'review/pages/OperationsReviewPage';
  static readonly LogCenterPage: string = 'log/pages/LogCenterPage';
  static readonly ArchiveLogQueryPage: string = 'log/pages/ArchiveLogQueryPage';
  static readonly OperationsLogQueryPage: string = 'log/pages/OperationsLogQueryPage';
}
