package com.rmf.rdvp.identity;

public enum PermissionCode {
    ARCHIVE_CENTER_DEVICE_ARCHIVE_QUERY,
    ARCHIVE_CENTER_DEVICE_ARCHIVE_CREATE_REQUEST_SUBMIT,
    ARCHIVE_CENTER_DEVICE_ARCHIVE_UPDATE_REQUEST_SUBMIT,
    ARCHIVE_CENTER_DEVICE_ARCHIVE_DELETE_REQUEST_SUBMIT,
    ARCHIVE_CENTER_DEVICE_ARCHIVE_QR_CODE_EXPORT,
    OPERATIONS_CENTER_DEVICE_VERIFICATION_SUBMIT,
    OPERATIONS_CENTER_DEVICE_FAULT_REPORT_SUBMIT,
    OPERATIONS_CENTER_REPAIR_TASK_ACCEPT,
    OPERATIONS_CENTER_REPAIR_REPORT_SUBMIT,
    OPERATIONS_CENTER_REINSPECTION_TASK_ACCEPT,
    OPERATIONS_CENTER_REINSPECTION_REPORT_SUBMIT,
    MANAGEMENT_CENTER_DEVICE_ARCHIVE_REQUEST_REVIEW,
    MANAGEMENT_CENTER_RECORD_QUERY
}


