package com.rmf.rdvp.identity;

public enum PermissionCode {
    ARCHIVE_DEVICE_READ,
    ARCHIVE_DEVICE_CREATE,
    ARCHIVE_DEVICE_DELETE,
    ARCHIVE_QRCODE_EXPORT,
    ARCHIVE_CHANGE_REQUEST_CREATE,
    OPS_DEVICE_VERIFY,
    OPS_FAULT_REPORT_CREATE,
    OPS_REPAIR_TASK_ACCEPT,
    OPS_REPAIR_REPORT_CREATE,
    OPS_REINSPECTION_CREATE,
    MGMT_ARCHIVE_CHANGE_REVIEW,
    MGMT_AUDIT_LOG_READ
}
